### PR TITLE
Full fix

### PR DESCRIPTION
**Pull request by OMGPandaYT**
fixed lots of flaws

### CODE REVIEW

**Comment by t0206** [comment]
Sry.
I don't have com.t0206
I also have com.advancedcheatblocker for this project

**Comment by OMGPandaYT** [comment]
The way your meant to do packages is:

<com, me, org, net>.<author>.<package>

You can just copy this code into your IDE and it should work perfectly fine.

**Comment by t0206** [comment]
I meaning I have advancedcheatblocker.com , so I using.
and Someone use com.gmail.xxxxxxxx.pl.... or com.name... or else. But I have domain . Soo i using it

**Comment by Dinty1** [comment]
> The way your meant to do packages is:
> 
> com,me,net,org.author.package

Incorrect. You're only supposed to use a domain that you actually have ownership of. Usually it's a good idea to do `io.github.username` if you don't own any other domain.

Though most people will own a similar domain to what you're saying so you're not *that* wrong :)

**Comment by OMGPandaYT** [comment]
For literally everything ive seen its something.author.package
So i use like me.omgpandayt.something

**Comment by Dinty1** [comment]
Because these people own a domain by that name (or are doing it wrong)

https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

**Comment by t0206** [comment]
Btw I have 25+ domains(com, net,info,me,jp.xyz,work,tokyo,biz,club).

**Pull request closed without merging**
